#!/bin/bash

sudo apt update

sudo apt install xmonad \
  libghc-xmonad-dev \
  libghc-xmonad-contrib-dev \
  xmobar \
  xcompmgr \
  nitrogen \
  stalonetray \
  moreutils \
  consolekit \
  synapse \
  ssh-askpass-gnome \
  thunar \
  terminator remmina

cp ~/.xmonad/.Xdefaults ~/
